{"name": "test_add[5-7-9]", "status": "failed", "statusDetails": {"message": "AssertionError: Test Failed!!!\nassert 9 == 12", "trace": "self = <Case.test_api.TestApi object at 0x101da4700>, a = 5, b = 7, expected = 9\n\n    @pytest.mark.parametrize(\"a,b,expected\", [(5, 7, 9),\n                                              (4, 4, 8),\n                                              (9, 9, 18),\n                                              (40, 40, 1),\n                                              (6, 5, 30)])\n    def test_add(self, a, b, expected):\n        sum = add(a, b)\n>       assert expected == sum, \"Test Failed!!!\"\nE       AssertionError: Test Failed!!!\nE       assert 9 == 12\n\n../PyAPI/Case/test_api.py:92: AssertionError"}, "attachments": [{"name": "log", "source": "6c69bfaa-8588-4e20-856b-9edd5162a789-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "f76bddb6-54a4-44da-b709-d7996f5ebc3a-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "5"}, {"name": "b", "value": "7"}, {"name": "expected", "value": "9"}], "start": 1585294252132, "stop": 1585294252132, "uuid": "43c85967-d531-4271-840b-f35909460f49", "historyId": "9412bf25fe39c542bd7d924fcb27b92f", "testCaseId": "05c2483b3a18cb5ad38bc6850b3b725a", "fullName": "Case.test_api.TestApi#test_add", "labels": [{"name": "parentSuite", "value": "Case"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "Parsons-Mac-mini.local"}, {"name": "thread", "value": "94963-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Case.test_api"}]}