{"name": "test_add[6-5-30]", "status": "failed", "statusDetails": {"message": "AssertionError: Test Failed!!!\nassert 30 == 11", "trace": "self = <Case.test_api.TestApi object at 0x101d6e2b0>, a = 6, b = 5\nexpected = 30\n\n    @pytest.mark.parametrize(\"a,b,expected\", [(5, 7, 9),\n                                              (4, 4, 8),\n                                              (9, 9, 18),\n                                              (40, 40, 1),\n                                              (6, 5, 30)])\n    def test_add(self, a, b, expected):\n        sum = add(a, b)\n>       assert expected == sum, \"Test Failed!!!\"\nE       AssertionError: Test Failed!!!\nE       assert 30 == 11\n\n../PyAPI/Case/test_api.py:92: AssertionError"}, "attachments": [{"name": "log", "source": "5dac533e-ab7d-46b1-803a-52bb84002e20-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "9348e3f0-8076-40b8-b801-ff2ac6b760d6-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "6"}, {"name": "b", "value": "5"}, {"name": "expected", "value": "30"}], "start": 1585294252170, "stop": 1585294252170, "uuid": "11612121-502d-444a-9bb0-a4e095cd55b9", "historyId": "7ffec18e6ad14e510e02773f1d423d53", "testCaseId": "05c2483b3a18cb5ad38bc6850b3b725a", "fullName": "Case.test_api.TestApi#test_add", "labels": [{"name": "parentSuite", "value": "Case"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "Parsons-Mac-mini.local"}, {"name": "thread", "value": "94963-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Case.test_api"}]}